config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  apipie
  root 'apipie/apipies#index'
  # USERS
  post '/shops/sign_in', to: 'authentication#authenticate'
  post '/shops/sign_up', to: 'authentication#sign_up'
  post '/players/sign_in', to: 'authentication#authenticate'
  post '/players/sign_up', to: 'authentication#sign_up'

  # COMPANIES
  get '/companies/all', to: 'companies#all'
  post '/companies/payment', to: 'companies#payment'
  resources :users
  resources :companies
  get '/location', to: 'companies#location'
  # GAMES
  resources :discounts
  resources :games
  resources :game_lists
  get '/games/:id/editor', to: 'games#editt', as: 'editor'
  post '/games/:id', to: 'games#update', as: 'perso'
  get '/games/:id/delete', to: 'games#destroy'
  get '/recap/:id', to: "games#recap", as: 'recap'
  post '/email', to: 'users#email'

  resources :targets

  # REPORT
  resources :scores
  get '/stats', to: 'scores#stats', as: 'scores_stats'
  get '/stats_games', to: 'scores#stats_games'
end

app/models/target.rb
class Target < ApplicationRecord
  has_and_belongs_to_many  :games
  has_many :scores
  belongs_to :company, foreign_key: 'company_id'
  mount_base64_uploader :image, ImageUploader
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_target, only: [:show, :edit, :update, :destroy]

  # GET /targets
  # GET /targets.json
  def index
    @targets = Target.all
  end

  # GET /targets/1
  # GET /targets/1.json
  def show
  end

  # GET /targets/new
  def new
    @target = Target.new
    access_key = '16e5c472cbad4e592e977029af54b1500b551362'
    secret_key = '932998f43862357f0da1a3e9b0340f5b38c55eb1'
    connection = Vws::Api.new(access_key, secret_key)
    width = 32
    active_flag = true
    application_metadata = nil
    puts @target.image.inspect
    puts vuforia_return = "ok"
    vuforia_return = connection.add_target(target_name, "http://api.playarshop.com" + @target.image.url, width, active_flag, application_metadata)
    # vuforia_return = connection.add_target(target_name, "./public/logo.png", width, active_flag, application_metadata)
    puts vuforia_return.inspect
  end

  # GET /targets/1/edit
  def edit
  end

  # POST /targets
  # POST /targets.json
  api :POST, '/targets', "Créer un ou plusieurs cible"
  description <<-EOS
    === Requête
      Doit avoir une image
      {
        "target": [{
            "place": "rennes",
            "city": "RENNES",
            "image": "data:image/png;base64," + logo en hexa
          }, {
            "place": "Germont",
            "city": "RENNES",
            "image": "data:image/png;base64," + target en hexa
          }]
       }
    === Réponse
      Code OK => 201
      {
        "game_ref": "968aff72907b7784d0253b0be5aecc63c8648fca"
      }

  EOS
  error :code => 401, :desc => "Non autorisé"
  error :code => 400, :desc => "Pas d'image"
  def create
    @user = User.find_by(id: current_user.id)
    print @user.inspect
    @company = Company.find_by(user_id: @user.id)
    game_id = Digest::SHA1.hexdigest([Time.now, rand].join)
    targets_params = params.require(:target)
    access_key = '16e5c472cbad4e592e977029af54b1500b551362'
    secret_key = '932998f43862357f0da1a3e9b0340f5b38c55eb1'
    connection = Vws::Api.new(access_key, secret_key)
    width = 32
    active_flag = true
    application_metadata = nil
    targets_params.each do |t|
      @company.targets.create(t.permit(:vuforia_name, :transaction_id, :target_id, :image, :path, :place, :city, :discountChance, :discountRate))
      @target = @company.targets.last
      target_name = Digest::SHA1.hexdigest([Time.now, rand].join)
      if @target.image.url.nil?
        return render json: {"error": "No Image"}, status: 302
      end
      # vuforia_return = connection.add_target(target_name, "http://api.playarshop.com" + @target.image.url, width, active_flag, application_metadata)
      vuforia_return = connection.add_target(target_name, "http://localhost:3000" + @target.image.url, width, active_flag, application_metadata)
      print vuforia_return.inspect
      connection_hash = JSON.parse(vuforia_return)
      @target.vuforia_name = target_name
      @target.transaction_id = game_id
      @target.save
    end
    # @target = Target.new(target)
    puts vuforia_return = "ok"
    # vuforia_return = connection.add_target("target_name", "./public/logo.png", width, active_flag, application_metadata)
    puts vuforia_return.inspect

    # respond_to do |format|
      # if @company.targets.save
        # format.html { redirect_to @target, notice: 'Targetqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq was successfully created.' }
    return render json:{  "game_ref": game_id }, status: 201
      # else
        # format.html { render :new }
        # return render json: { render json: {"target": "errors"}, status: :unprocessable_entity }
        # return render json:{  "status": "created" }, status: 401
      # end11111
    # end
  end

  # PATCH/PUT /targets/1
  # PATCH/PUT /targets/1.json
  def update
    respond_to do |format|
      if @target.update(target_params)
        format.html { redirect_to @target, notice: 'Target was successfully updated.' }
        format.json { render :show, status: :ok, location: @target }
      else
        format.html { render :edit }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1
  # DELETE /targets/1.json
  def destroy
    @target.destroy
    respond_to do |format|
      format.html { redirect_to targets_url, notice: 'Targetsssssssssssssssssssssssssss was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target
      access_key = '16e5c472cbad4e592e977029af54b1500b551362'
      secret_key = '932998f43862357f0da1a3e9b0340f5b38c55eb1'
      connection = Vws::Api.new(access_key, secret_key)
      width = 32
      active_flag = true
      application_metadata = nil
      puts @target.image.inspect
      puts vuforia_return = "ok"
      # vuforia_return = connection.add_target(target_name, "http://api.playarshop.com" + @target.image.url, width, active_flag, application_metadata)
      vuforia_return = connection.add_target(target_name, "./public/logo.png", width, active_flag, application_metadata)
      puts vuforia_return.inspect
      @target = Target.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def target_params
      params.require(:target).permit(:vuforia_name, :transaction_id, :target_id, :image, :path, :place, :city, :discountChance, :discountRate)
    end
end

app/helpers/targets_helper.rb
module TargetsHelper
    def init_vuforia
        print 'vuforia'
    end
end

app/views/targets/_form.html.erb
<%= form_for(target) do |f| %>
  <% if target.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(target.errors.count, "error") %> prohibited this target from being saved:</h2>

      <ul>
      <% target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vuforia_name %>
    <%= f.text_field :vuforia_name %>
  </div>

  <div class="field">
    <%= f.label :transaction_id %>
    <%= f.text_field :transaction_id %>
  </div>

  <div class="field">
    <%= f.label :target_id %>
    <%= f.text_field :target_id %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :path %>
    <%= f.text_field :path %>
  </div>

  <div class="field">
    <%= f.label :place %>
    <%= f.text_field :place %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :discountChance %>
    <%= f.text_field :discountChance %>
  </div>

  <div class="field">
    <%= f.label :discountRate %>
    <%= f.text_field :discountRate %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/targets/edit.html.erb
<h1>Editing Target</h1>

<%= render 'form', target: @target %>

<%= link_to 'Show', @target %> |
<%= link_to 'Back', targets_path %>

app/views/targets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Targets</h1>

<table>
  <thead>
    <tr>
      <th>Vuforia name</th>
      <th>Transaction</th>
      <th>Target</th>
      <th>Image</th>
      <th>Path</th>
      <th>Place</th>
      <th>City</th>
      <th>Discountchance</th>
      <th>Discountrate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @targets.each do |target| %>
      <tr>
        <td><%= target.vuforia_name %></td>
        <td><%= target.transaction_id %></td>
        <td><%= target.target_id %></td>
        <td><%= target.image %></td>
        <td><%= target.path %></td>
        <td><%= target.place %></td>
        <td><%= target.city %></td>
        <td><%= target.discountChance %></td>
        <td><%= target.discountRate %></td>
        <td><%= link_to 'Show', target %></td>
        <td><%= link_to 'Edit', edit_target_path(target) %></td>
        <td><%= link_to 'Destroy', target, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Target', new_target_path %>

app/views/targets/new.html.erb
<h1>New Target</h1>

<%= render 'form', target: @target %>

<%= link_to 'Back', targets_path %>

app/views/targets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vuforia name:</strong>
  <%= @target.vuforia_name %>
</p>

<p>
  <strong>Transaction:</strong>
  <%= @target.transaction_id %>
</p>

<p>
  <strong>Target:</strong>
  <%= @target.target_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @target.image %>
</p>

<p>
  <strong>Path:</strong>
  <%= @target.path %>
</p>

<p>
  <strong>Place:</strong>
  <%= @target.place %>
</p>

<p>
  <strong>City:</strong>
  <%= @target.city %>
</p>

<p>
  <strong>Discountchance:</strong>
  <%= @target.discountChance %>
</p>

<p>
  <strong>Discountrate:</strong>
  <%= @target.discountRate %>
</p>

<%= link_to 'Edit', edit_target_path(@target) %> |
<%= link_to 'Back', targets_path %>