config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  apipie
  root 'apipie/apipies#index'
  # USERS
  post '/shops/sign_in', to: 'authentication#authenticate'
  post '/shops/sign_up', to: 'authentication#sign_up'
  post '/players/sign_in', to: 'authentication#authenticate'
  post '/players/sign_up', to: 'authentication#sign_up'

  # COMPANIES
  get '/companies/all', to: 'companies#all'
  post '/companies/payment', to: 'companies#payment'
  resources :users
  resources :companies
  get '/location', to: 'companies#location'
  # GAMES
  resources :discounts
  resources :games
  resources :game_lists
  get '/games/:id/editor', to: 'games#editt', as: 'editor'
  post '/games/:id', to: 'games#update', as: 'perso'
  get '/games/:id/delete', to: 'games#destroy'
  get '/recap/:id', to: "games#recap", as: 'recap'
  post '/email', to: 'users#email'

  resources :targets

  # REPORT
  resources :scores
  get '/stats', to: 'scores#stats', as: 'scores_stats'
  get '/stats_games', to: 'scores#stats_games'
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :company, foreign_key: 'company_id'
  has_and_belongs_to_many  :target
  has_one :discount
  has_one :game_list
  mount_base64_uploader :image, ImageUploader
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:edit, :update, :destroy]

  # GET /games
  # GET /games.json
  api :GET, '/games ', "Récupérer les jeux personnalisés"
  description <<-EOS
    === Autorisation nécessaire
    === Status
      200
    === Réponse
      {
        "games": [
          {
            "id": 1,
            "game_ref": "",
            "ref": "d",
            "description": "sd",
            "image": null,
            "color1": "",
            "color2": ""
          },
          {
            "id": 2,
            "game_ref": "",
            "ref": "sdd",
            "description": "",
            "image": "/uploads/9fc7bc05-c5b5-4885-8795-4b377f83d3ea.gif",
            "color1": "",
            "color2": ""
          }
        ]
      }
  EOS
  error :code => 401, :desc => "Vuforia name not found"
  def index
    if @current_user.company.last.nil?
      return render json: {  "error": "No company" }, status: 200
    end
    @games = @current_user.company.last.games.all
    if @games.nil?
      return render json: {  "error": "No games" }, status: 200
    end
  end


  api :GET, '/games/:vuforia_name', "Récupérer un jeu"
  api :GET, '/games/:id', "Récupérer un jeu"
  description <<-EOS
    === Autorisation nécessaire
      Aucune autorisation n'est nécessaire pour effectuer cette action. Un token est retourné pour pouvoir ensuite effectuer les actions nécessitant une autorisation.
    === Status
      200
    === Réponse
      {
        "id": 3,
        "ref": 1,
        "name": "Ballons ",
        "description": "Eclates les ballons",
        "logo": "logo en base 64",
        "color1": "rouge",
        "color2": "bleu",
        "perso1": "Jeu de Jacquie",
        "perso2": "et Michèle",
        "custom": "custom",
        "discount": "Vous avez gagné 42% de réduction",
        "vuforia_name": "189d6c2a8a5ad19fc1aa2c89c9d57850c4770470"
      }
  EOS
  error :code => 401, :desc => "Vuforia name not found"
  param :vuforia_name, String, :desc => "Nom de la cible retourné par Vuforia quand détecté", :required => false
  param :name, String, :desc => "Nom du jeu", :required => false
  param :logo, String, :desc => "Logo en base 64", :required => false
  param :color1, String, :desc => "Personnalisation couleur 1", :required => false
  param :color2, String, :desc => "Personnalisation couleur 2", :required => false
  param :perso2, String, :desc => "Personnalisation 1", :required => false
  param :perso1, String, :desc => "Personnalisation 2", :required => false
  param :custom, String, :desc => "Customisation", :required => false
  def show
    @targets = Target.where(transaction_id: params.require(:id))
    if @targets.empty?
       @targets = Target.where(vuforia_name: params.require(:id))
       @targets = Target.where(transaction_id: @targets.first.transaction_id)
    end
    @game = Game.where(perso1: @targets[0].transaction_id)
    print @game.inspect
    if @game.nil?
      return render :json => { "error": "no games"}, status: 422
    end
    return render :json => {
      :targets => @targets.as_json(),
      :game => @game.as_json()
    }, status: 200
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  api :GET, '/games/:id/editor', "Récupérer les images"
  description <<-EOS
    === Status
      Requête pour que l'outil d'édition récupère les targets.
      si ok => 200
    === Réponse
        {
          "company": {
            "id": 9,
            "name": "playarshop",
            "logo": {
              "url": "/uploads/b1748668-89a1-4bdf-b937-ebb6ab66f4fd.gif"
            },
            "siret": "",
            "company_id_id": null,
            "user_id": 2,
            "created_at": "2017-01-01T18:25:51.495Z",
            "updated_at": "2017-01-01T21:36:01.327Z"
          },
          "games": [
            {
              "id": 15,
              "ref": "2",
              "name": "Name 1",
              "description": "Vise le verre1",
              "logo": "",
              "image": {
                "url": "/uploads/4c101277-3dc5-4d61-b2ab-0213ce46f99d.png"
              },
              "color1": "#8F3985",
              "color2": "#61E786",
              "perso1": "e53a1542e9170ccacefa71cc5fb9b3732577907a",
              "perso2": "Bloblo",
              "custom": "custom",
              "vuforia_name": "",
              "company_id": 1,
              "target_id": null,
              "created_at": "2017-01-01T20:53:10.250Z",
              "updated_at": "2017-01-01T21:00:56.306Z"
            },
            {
              "id": 16,
              "ref": "2",
              "name": "Name 2",
              "description": "Vise le verre2",
              "logo": "",
              "image": {
                "url": "/uploads/50187b4e-5e62-455c-8796-1c39b27d0ef0.png"
              },
              "color1": "#8F3985",
              "color2": "#61E786",
              "perso1": "e53a1542e9170ccacefa71cc5fb9b3732577907a",
              "perso2": "Bloblo",
              "custom": "custom",
              "vuforia_name": "",
              "company_id": 1,
              "target_id": null,
              "created_at": "2017-01-01T20:53:10.753Z",
              "updated_at": "2017-01-01T21:01:12.409Z"
            }
          ],
          "targets": [
            {
              "id": 27,
              "vuforia_name": "b5d8d934b0a6b04a59c3d60771a8142ccca33234",
              "transaction_id": "e53a1542e9170ccacefa71cc5fb9b3732577907a",
              "target_id": null,
              "image": {
                "url": "/uploads/78a5b18a-4091-4182-b49e-5fb3185069e5.png"
              },
              "path": null,
              "place": "rennes",
              "city": "RENNES",
              "discountChance": null,
              "discountRate": null,
              "company_id": 1,
              "game_id": null,
              "created_at": "2017-01-01T20:52:52.765Z",
              "updated_at": "2017-01-01T20:52:57.240Z"
            },
            {
              "id": 28,
              "vuforia_name": "fd8d1472ac166ce43f407b4b914e9ebcfe273bf0",
              "transaction_id": "e53a1542e9170ccacefa71cc5fb9b3732577907a",
              "target_id": null,
              "image": {
                "url": "/uploads/6dbd56c1-cf33-445d-8fc8-9e02fbd94a46.png"
              },
              "path": null,
              "place": "Germont",
              "city": "RENNES",
              "discountChance": null,
              "discountRate": null,
              "company_id": 1,
              "game_id": null,
              "created_at": "2017-01-01T20:52:57.282Z",
              "updated_at": "2017-01-01T20:53:09.743Z"
            }
          ]
    }
  EOS
  error :code => 401, :desc => "Vuforia name not found"
  param :id, String, :desc => "Game REF", :required => true
  param :logo_image, String, :desc => "Image du logo", :required => false
  param :target_image, String, :desc => "Image de la target", :required => false
  def editt
    @shop = User.find_by(id: @current_user.id)
    @company = Company.find_by(user_id: @shop.id)
    @games = Game.where(perso1: params[:id])
    @targets = Target.where(transaction_id: params[:id])
    return render :json => {
      :company =>@company.as_json(),
      :games =>@games.as_json(),
      :targets =>@targets.as_json()
    }, status: 200
  end

  api :GET, '/recap/:id', "Résumé des informations "
  description <<-EOS
    === Status
      Requête pour que la confirmation de la création du jeu.
      si ok => 200
    === Réponse
      {
        "company": {
          "name": "playarshop",
          "logo": "base64_image"
        },
        "target": {
          "place": "rennes",
          "image": "base64_image"
        },
        "game": {
              "ref": 1,
              "name": "Ballons ",
              "description": "Eclates les ballons",
              "logo": "logo",
              "color1": "rouge",
              "color2": "bleu",
              "perso1": "Jeu de Jacquie",
              "perso2": "et Michèle",
              "custom": "custom"
          }
          "discount": {
                "success": "Bravo, vous avez gagné 42%",
                "fail": "Raté !"
          }
       }
  EOS
  error :code => 401, :desc => "Vuforia name not found"
  param :id, String, :desc => "ID du Game", :required => true
  param :logo_image, String, :desc => "Image du logo", :required => false
  param :target_image, String, :desc => "Image de la target", :required => false
  def recap
    game_ref = params.require(:id)
    @user = User.find_by(id: @current_user.id)
    @target = Target.find_by(transaction_id: game_ref)
    @company = Company.find_by(user_id: @current_user.id)
    @game = Game.find_by(perso1: game_ref)
    @discount = Discount.find_by(game_ref: game_ref)
  end

  api :POST, '/games/:id', "Changer information du User"
  description <<-EOS
    === Request
    {
      "id": 4,
      "ref": "4",
      "name": "Chasse au tresor",
      "description": "Trouves toutes les cibles",
      "color1": "#8F3985",
      "color2": "#61E786",
      "company_id": 5,
      }
    === Réponse
  EOS
  error :code => 401, :desc => "Non autorisé"
  param :name, String, :desc => "Nom du jeu", :required => false
  def target_get_games
    puts @current_user.inspect
    @shop = User.find_by(id: @current_user.id)
    puts @shop.inspect
    @company = Company.find_by(id: @shop.company_id)
    @games = Game.find_by(id: @shop.company_id)
    puts @games.inspect
    @games = @company.games
  end

  # POST /games
  # POST /games.json
  api :POST, '/games', "Créer un ou plusieurs personnalisation de jeu"
  description <<-EOS
    === Requête

app/helpers/games_helper.rb
module GamesHelper

    def format_game(ref)
        ref = GameList.find_by(id: ref).name
    end
end

app/views/games/_form.html.erb
<%= form_for(game) do |f| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ref %>
    <%= f.text_field :ref %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :logo %>
    <%= f.text_field :logo %>
  </div>

  <div class="field">
    <%= f.label :color1 %>
    <%= f.text_field :color1 %>
  </div>

  <div class="field">
    <%= f.label :color2 %>
    <%= f.text_field :color2 %>
  </div>

  <div class="field">
    <%= f.label :perso1 %>
    <%= f.text_field :perso1 %>
  </div>

  <div class="field">
    <%= f.label :perso2 %>
    <%= f.text_field :perso2 %>
  </div>

  <div class="field">
    <%= f.label :custom %>
    <%= f.text_field :custom %>
  </div>

  <div class="field">
    <%= f.label :discount %>
    <%= f.text_field :discount %>
  </div>

  <div class="field">
    <%= f.label :vuforia_name %>
    <%= f.text_field :vuforia_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Ref</th>
      <th>Name</th>
      <th>Description</th>
      <th>Logo</th>
      <th>Color1</th>
      <th>Color2</th>
      <th>Perso1</th>
      <th>Perso2</th>
      <th>Custom</th>
      <th>Discount</th>
      <th>Vuforia name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.ref %></td>
        <td><%= game.name %></td>
        <td><%= game.description %></td>
        <td><%= game.logo %></td>
        <td><%= game.color1 %></td>
        <td><%= game.color2 %></td>
        <td><%= game.perso1 %></td>
        <td><%= game.perso2 %></td>
        <td><%= game.custom %></td>
        <td><%= game.discount %></td>
        <td><%= game.vuforia_name %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ref:</strong>
  <%= @game.ref %>
</p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @game.logo %>
</p>

<p>
  <strong>Color1:</strong>
  <%= @game.color1 %>
</p>

<p>
  <strong>Color2:</strong>
  <%= @game.color2 %>
</p>

<p>
  <strong>Perso1:</strong>
  <%= @game.perso1 %>
</p>

<p>
  <strong>Perso2:</strong>
  <%= @game.perso2 %>
</p>

<p>
  <strong>Custom:</strong>
  <%= @game.custom %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @game.discount %>
</p>

<p>
  <strong>Vuforia name:</strong>
  <%= @game.vuforia_name %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>