config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  apipie
  root 'apipie/apipies#index'
  # USERS
  post '/shops/sign_in', to: 'authentication#authenticate'
  post '/shops/sign_up', to: 'authentication#sign_up'
  post '/players/sign_in', to: 'authentication#authenticate'
  post '/players/sign_up', to: 'authentication#sign_up'

  # COMPANIES
  get '/companies/all', to: 'companies#all'
  post '/companies/payment', to: 'companies#payment'
  resources :users
  resources :companies
  get '/location', to: 'companies#location'
  # GAMES
  resources :discounts
  resources :games
  resources :game_lists
  get '/games/:id/editor', to: 'games#editt', as: 'editor'
  post '/games/:id', to: 'games#update', as: 'perso'
  get '/games/:id/delete', to: 'games#destroy'
  get '/recap/:id', to: "games#recap", as: 'recap'
  post '/email', to: 'users#email'

  resources :targets

  # REPORT
  resources :scores
  get '/stats', to: 'scores#stats', as: 'scores_stats'
  get '/stats_games', to: 'scores#stats_games'
end

app/models/discount.rb
class Discount < ApplicationRecord
    belongs_to :game, foreign_key: 'game'
    belongs_to :company, foreign_key: 'company_id'
end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController
  before_action :set_discount, only: [:show, :edit, :update, :destroy]

  # GET /discounts
  # GET /discounts.json
  # def index
  #   @discounts = Discount.all
  # end
  api :GET, '/discounts', "Application mobile récupère les scores"
  description <<-EOS
    === Réponse
      {
        "discount": [
          {
            "name": "playarshop",
            "success": "Vous avez gagné 42% de réduction",
            "created_at": "2016-07-20T23:27:20.610Z"
          },
          {
            "name": "playarshop",
            "success": "Vous avez gagné 42% de réduction",
            "created_at": "2016-07-20T23:48:29.492Z"
          },
          {
            "name": "playarshop",
            "success": "Vous avez gagné 42% de réduction",
            "created_at": "2016-07-20T23:48:45.889Z"
          }
        ]
      }
  EOS
  formats ['json']
  param :game_id, String, :desc => "id du jeu persionnalisé", :required => false
  param :score, String, :desc => "Score effectué", :required => false
  param :reduction, String, :desc => "Réduction à afficher", :required => false
  def index
    puts current_user.id
    @scores = Score.all.where(player_id: current_user.id)
    puts Score.all.inspect
    @discount = Discount.all
    puts @discount.inspect
    @finale = Array.new
    @array = []
    @scores.each do |i|
      game = Game.find_by(id: i.game_id)
      res = @discount.find_by(game_ref: game.perso1)
      if i.location_gps == "win"
        if  !res.nil?
          name = Company.find_by(id: res.company_id)
          @hash = { :name => name.name, :success => res.success, :created_at => i.created_at }
          @array.push(@hash)
        end
      end
    end
    render "index.json.jbuilder"
  end
  # GET /discounts/1
  # GET /discounts/1.json
  def show
  end

  # GET /discounts/new
  def new
    @discount = Discount.new
  end

  # GET /discounts/1/edit
  def edit
  end

  api :POST, '/discounts', "Créer un ou plusieurs réductions"
  description <<-EOS
    === Requête
      Doit avoir une image
      Doit avoir le meme nombre de personnlisation que le nombre de Target
      {
        "game_ref": "968aff72907b7784d0253b0be5aecc63c8648fca",
        "discount": [{
          "success": "Trouves la licorne",
          "fail": "Trouves la licorne quand même"
        },{
          "success": "Bien joué tu l'as trouvé",
          "fail": "Tu l'as quand même trouvé"
        }]
      }
    === Réponse
      code 201 OK
  EOS
  error :code => 401, :desc => "Non autorisé"
  error :code => 422, :desc => "Pas de company"
  param :game_ref, String, :desc => "Référence du jeu à personnaliser", :required => true
  param :discount, Array, :desc => "Personnlisation du jeu", :required => true
  def create
    @user = User.find_by(id: current_user.id)
    @company = Company.find_by(user_id: current_user.id)
    game_ref = params.require(:game_ref)
    if @company.nil?
      return render :json =>{ "error": "no company"}, status: 422
    end
    game_ref = params.require(:game_ref)
    discounts = params.require(:discount)
    discounts.each do |d|
      @company.discounts.create(d.permit(:level, :success, :fail, :state))
      @discount = @company.discounts.last
      @discount.game_ref = game_ref
      @discount.save
    end
    return render json: {"success": "success"}, status: 201
  end

  # PATCH/PUT /discounts/1
  # PATCH/PUT /discounts/1.json
  def update
    respond_to do |format|
      if @discount.update(discount_params)
        format.html { redirect_to @discount, notice: 'Discount was successfully updated.' }
        format.json { render :show, status: :ok, location: @discount }
      else
        format.html { render :edit }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discounts/1
  # DELETE /discounts/1.json
  def destroy
    @discount.destroy
    respond_to do |format|
      format.html { redirect_to discounts_url, notice: 'Discount was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_discount
      @discount = Discount.find(params[:id])
    end

    def discount_params
      params.require(:discount).permit(:level, :success, :fail, :state)
    end
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/views/discounts/_form.html.erb
<%= form_for(discount) do |f| %>
  <% if discount.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discount.errors.count, "error") %> prohibited this discount from being saved:</h2>

      <ul>
      <% discount.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :level %>
    <%= f.text_field :level %>
  </div>

  <div class="field">
    <%= f.label :success %>
    <%= f.text_field :success %>
  </div>

  <div class="field">
    <%= f.label :fail %>
    <%= f.text_field :fail %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discounts/edit.html.erb
<h1>Editing Discount</h1>

<%= render 'form', discount: @discount %>

<%= link_to 'Show', @discount %> |
<%= link_to 'Back', discounts_path %>

app/views/discounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Discounts</h1>

<table>
  <thead>
    <tr>
      <th>Level</th>
      <th>Success</th>
      <th>Fail</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discounts.each do |discount| %>
      <tr>
        <td><%= discount.level %></td>
        <td><%= discount.success %></td>
        <td><%= discount.fail %></td>
        <td><%= discount.state %></td>
        <td><%= link_to 'Show', discount %></td>
        <td><%= link_to 'Edit', edit_discount_path(discount) %></td>
        <td><%= link_to 'Destroy', discount, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discount', new_discount_path %>

app/views/discounts/new.html.erb
<h1>New Discount</h1>

<%= render 'form', discount: @discount %>

<%= link_to 'Back', discounts_path %>

app/views/discounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Level:</strong>
  <%= @discount.level %>
</p>

<p>
  <strong>Success:</strong>
  <%= @discount.success %>
</p>

<p>
  <strong>Fail:</strong>
  <%= @discount.fail %>
</p>

<p>
  <strong>State:</strong>
  <%= @discount.state %>
</p>

<%= link_to 'Edit', edit_discount_path(@discount) %> |
<%= link_to 'Back', discounts_path %>